### ISSUE TITLE
exit -2147483648

### ISSUE THREAD

**Issue by rphlr** [rphlr/42-minishell#14]
Minishell entering in an **infinite loop** and we cannot stop it until we just force quit the terminal... 😭

**Comment by rphlr** [comment]
Same with `exit -2147483649`

**Comment by Maria-esther0** [comment]
> Minishell entering in an **infinite loop** and we cannot stop it until we just force quit the terminal... 😭

kel dommage 😿 fo regler sa

**Comment by rphlr** [comment]
c tro kool c tt réparé lol

**Comment by rphlr** [comment]
Fuck this shitty exit... Error was when initializing token.. If it detects an 'arg' it was blocked in a infinite loop... That's pretty stupid because I was stuck on that for all the day 🥲
